<?php
require_once('media.php');
require_once('mediawiki.php');
require_once( 'plugins.php');
require_once( 'site.php');
require_once('themes.php');
require_once( 'wp_functions.php');
require_once( 'utils.php');
require_once( 'WPQuery.php');
require_once( 'functions.php');
require_once( 'wpdb.php');
require_once('Walker.php');
require_once( 'hooks.php' );
require_once( 'post.php' );
require_once( 'formatting.php' );
require_once( 'i18n.php' );
require_once( 'categories.php' );
require_once( 'css.php' );
require_once( 'actions.php' );
require_once( 'filters.php' );
require_once( 'screen.php' );
require_once( 'js.php' );
require_once( 'config.php' );
require_once('query.php');
require_once( 'options.php');
require_once( 'link-template.php');
require_once( 'kses.php' );
require_once( 'logo.php');
require_once( 'menus.php');
require_once( 'template.php' );